//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.CrashReporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.CrashReporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
   
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string CrashReporting_CrashReportWindow_Expander_Header_ShowDetails {
            get {
                return ResourceManager.GetString("CrashReporting_CrashReportWindow_Expander_Header_ShowDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string CrashReporting_CrashReportWindow_TextBlock_Text_Comments {
            get {
                return ResourceManager.GetString("CrashReporting_CrashReportWindow_TextBlock_Text_Comments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In order for us to fix this issue please provide some details about what you were doing and report us using button below..
        /// </summary>
        internal static string CrashReporting_CrashReportWindow_TextBlock_Text_InOrderForUsToFixThisIssuePleaseProvideSomeDetailsAboutWhatYouWereDoingAndReportUsUsingButtonBelow {
            get {
                return ResourceManager.GetString("CrashReporting_CrashReportWindow_TextBlock_Text_InOrderForUsToFixThisIssuePleaseProvideSomeDetailsAboutWhatYouWereDoingAndReportUsUsingButtonBelow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please tell us briefly what you were doing.
        /// </summary>
        internal static string CrashReporting_AdditionalInfoView_TextBlock_Text_PleaseTellUsBrieflyWhatYouWereDoing {
            get {
                return ResourceManager.GetString("CrashReporting_AdditionalInfoView_TextBlock_Text_PleaseTellUsBrieflyWhatYouWereDoing", resourceCulture);
            }
        }
 }
}